### ISSUE TITLE
ESO+ Bank

### ISSUE THREAD

**Issue by Thiana** [m7andrew/ItemScripting#1]
The current version of the addon appears to ignore the extended bank space offered by ESO+. Any chance you could release an update with subscriber bank support? Thanks.

**Comment by m7andrew** [comment]
Unfortunately, I don't have ESO+ to test this. However, I think I may have found the issue. I originally used [`GetBagSize`](https://wiki.esoui.com/GetBagSize), which might ignore ESO+ bank space. I changed it to use `GetBagUseableSize`. The function is undocumented, but It appears to work the same. I'm hoping it takes ESO+ bank space into account. Let me know if the update fixed the problem.
